apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic3tier-ui
  template:
    metadata:
      labels:
        app: basic3tier-ui
    spec:
      containers:
      - name: ui-container
        image: sribeeram/basic3tier-ui:latest
        ports:
        - containerPort: 80
        # Optional environment variable if using dynamic config
        # env:
        # - name: API_URL
        #   value: "http://api-service"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: three-tier
spec:
  selector:
    app: basic3tier-ui
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
